server.port: 8081
spring.profiles.include: redis

spring:
  main:
    allow-bean-definition-overriding: true

# 추후 환경별 도메인 추가 시, 해당 도메인으로 설정 변경 필요

redis.auth-key: 'auth'

jwt:
  secret-key: default-secret
  expiration: 86400

growing-shop:
  endpoints:
    audience: http://localhost:8082
    order: http://localhost:8083
    product: http://localhost:8084
  cloud-gateway-predicate:
    audience: AUDIENCE
    order: ORDER
    product: PRODUCT

---

spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
  h2.console:
    port: 8090
  sql.init:
    mode: always
    schema-locations: classpath:local/*_init.sql

---

spring:
  config.activate.on-profile: acceptance
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
