CREATE TABLE company (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    business_registration_number VARCHAR(10),
    status VARCHAR(20) NOT NULL COMMENT 'NORMAL|UNDER_REVIEW',
    grade VARCHAR(20) NOT NULL DEFAULT 'BRONZE' COMMENT 'BRONZE|SILVER|GOLD|PLATINUM|DIAMOND',

    PRIMARY KEY (id)
);

CREATE TABLE user (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    mobile VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login_id VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    company bigint(20),
    status VARCHAR(20) NOT NULL COMMENT 'NORMAL|UNDER_REVIEW|WITHDRAWAL',
    type VARCHAR(20) NOT NULL COMMENT 'NORMAL|SELLER|ADMIN',
    grade VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL|VIP|VVIP|MASTER',

    PRIMARY KEY (id),
    CONSTRAINT company FOREIGN KEY (company) REFERENCES company(id)
);
