validation.constraints:
  small-letter: "^[a-z]+$"
  big-letter: "^[A-Z]+$"
  korean: "^[?-?]+$"
  number: "^[\\d]+$"
  small-big-letter: "^[a-zA-Z]+$"
  small-letter-korean: "^[a-z?-?]+$"
  small-letter-number: "^[a-z\\d]+$"
  big-letter-korean: "^[A-Z?-?]+$"
  big-letter-number: "^[A-Z\\d]+$"
  korean-number: "^[?-?\\d]+$"
  small-big-letter-korean: "^[a-zA-Z?-?]+$"
  small-big-letter-number: "^[a-zA-Z\\d]+$"
  big-letter-korean-number: "^[A-Z?-?\\d]+$"
  small-big-letter-korean-number: "^[a-zA-Z?-?\\d]+$"
