server.port: 8082
spring.profiles.include: security, redis

---

spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
  h2.console:
    enabled: true
    path: /h2-console
  sql.init:
    mode: always
    schema-locations: classpath:local/category_init.sql

---

spring:
  config.activate.on-profile: acceptance
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
